name: Testing Workflow

# Step 1: Choose the branch or branches you want to run this workflow
on: 
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
 
jobs:        
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project_dir: 
        - "java/advanced/BannerRecyclerViewExample"
        - "java/advanced/APIDemo"
        - "java/admob/AdaptiveBannerExample"
        - "java/admob/BannerExample"
        - "java/admob/RewardedVideoExample"
        - "java/admob/NativeAdvancedExample"
        - "java/admob/InterstitialExample"
        - "java/admanager/AdaptiveBannerExample"
        - "java/admanager/BannerExample"
        - "java/admanager/NativeAdsExample"
        - "java/admanager/RewardedVideoExample"
        - "java/admanager/InterstitialExample"
        - "kotlin/advanced/APIDemo"
        - "kotlin/admob/AdaptiveBannerExample"
        - "kotlin/admob/BannerExample"
        - "kotlin/admob/RewardedVideoExample"
        - "kotlin/admob/NativeAdvancedExample"
        - "kotlin/admob/InterstitialExample"
        - "kotlin/admanager/AdaptiveBannerExample"
        - "kotlin/admanager/BannerExample"
        - "kotlin/admanager/NativeAdsExample"
        - "kotlin/admanager/RewardedVideoExample"
        - "kotlin/admanager/InterstitialExample"

    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Clone Repo
        uses: actions/checkout@v1

      - name: Set commit range (push to the master branch, e.g. merge)
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: echo "COMMIT_RANGE="${{ github.event.before }}.."" >> $GITHUB_ENV
        
      - name: Set commit range (pull request)
        if: github.event_name == 'pull_request'
        run: echo "COMMIT_RANGE="HEAD~.."" >> $GITHUB_ENV
        
      - name: Build
        run: sh .github/workflows/build.sh
        env: 
          COMMIT_RANGE: ${{ env.COMMIT_RANGE }}
          PROJ_DIR: ${{ matrix.project_dir }}

